// Generated by CoffeeScript 1.6.2
/*
* A application view
*/


(function() {
  define(['jQueryUI', 'Backpack', 'SearchView', 'HistoryView'], function($, Backpack, SearchView, HistoryView) {
    return Backpack.View.extend({
      /*
      * Sets up main view
      */

      initialize: function(options) {
        var historyView, searchView;

        Backpack.View.prototype.initialize.apply(this, arguments);
        searchView = new SearchView({
          name: 'searchView'
        });
        historyView = new HistoryView({
          name: 'historyView'
        });
        this.stackView = new Backpack.StackView({
          children: [searchView, historyView],
          navigationEvents: {
            searchView: {
              event: 'onHistoryButtonClicked',
              target: 'historyView'
            },
            historyView: {
              event: 'onBackButtonClicked',
              back: true
            }
          },
          subscribers: {
            SHOW_VIEW: 'showChild'
          }
        });
        this.$el.append(this.stackView.$el);
      }
    });
  });

}).call(this);
