// Generated by CoffeeScript 1.6.2
/*
* A view to search for address
*/


(function() {
  define(['jQuery', 'Underscore', 'Backpack', 'LocationService', 'LocationItemView', 'text!template/SearchView.html'], function($, _, Backpack, LocationService, LocationItemView, viewTemplate) {
    var locationService;

    locationService = LocationService.getInstance();
    return Backpack.View.extend({
      template: _.template(viewTemplate),
      events: {
        'click #search-button': 'onSearchButtonClicked',
        'click #history-button': 'onHistoryButtonClicked'
      },
      subscribers: {
        SEARCH_ADDRESS: 'doSearch'
      },
      /*
      * Sets up main view
      */

      initialize: function(options) {
        var collection, searchListView;

        Backpack.View.prototype.initialize.apply(this, arguments);
        this.render();
        collection = this.collection = new Backpack.Collection(null, {
          model: Backpack.Model
        });
        searchListView = new Backpack.ListView({
          collection: collection,
          itemView: LocationItemView
        });
        this.$('#search-result-list').append(searchListView.$el);
        this.mapView = new Backpack.GoogleMapView({
          apiKey: 'AIzaSyDAJRmpbhxdAaoSYj2_iwaMEGxuxBR3YoM',
          subscribers: {
            INIT_GOOGLE_MAP: 'initMap',
            GOOGLE_MAP_SCRIPT_LOADED: '_onScriptLoaded'
          }
        });
        this.$('#map-container').append(this.mapView.$el);
      },
      /*
      * Renders template HTML
      */

      render: function() {
        this.$el.html(this.template());
        return this;
      },
      /*
      * Click event handler for [Search] button
      */

      onSearchButtonClicked: function() {
        this.doSearch($('#address-input').val());
      },
      /*
      * Makes API calls to get current location and search for a given address
      * @param {String} address an address to search for
      */

      doSearch: function(address) {
        var currentLocationCallbackObj, currentPos, searchCallbackObj,
          _this = this;

        this.setLoading(true);
        currentPos = null;
        searchCallbackObj = {
          success: function(data) {
            var modelData;

            console.log("search result: " + JSON.stringify(data));
            modelData = _.map(data.results, function(result) {
              result.distance = locationService.calculateDistance(currentPos, result.geometry.location);
              return result;
            });
            _this.collection.reset([modelData[0]]);
            _this.mapView.setLocation(modelData[0].geometry.location);
            Backbone.trigger('ADD_LOCATION_HISTORY', _this.collection.models, {
              at: 0
            });
            _this.setLoading(false);
          },
          failure: function(error) {
            _this.setLoading(false);
            console.log('search error: ' + error);
          }
        };
        currentLocationCallbackObj = {
          success: function(pos) {
            currentPos = {
              lat: pos.coords.latitude,
              lng: pos.coords.longitude
            };
            console.log("current position: " + JSON.stringify(pos));
            locationService.search(address, searchCallbackObj);
          },
          failure: function(error) {
            _this.setLoading(false);
            console.log('current location error: ' + error);
          }
        };
        locationService.getCurrentLocation(currentLocationCallbackObj);
      },
      /*
      * Toggles loading mode of this view
      * @param {Boolean} isLoading a flag to specify loading mode or not
      */

      setLoading: function(isLoading) {
        $('#search-result-container').toggleClass('loading', isLoading);
      },
      /*
      * Click event handler for [History] button
      */

      onHistoryButtonClicked: function() {}
    });
  });

}).call(this);
